config/routes.rb
Rails.application.routes.draw do
  resources :names
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/form_add", to: "home#add_form"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/csv_datum.rb
class CsvDatum < ApplicationRecord
    
    def self.to_csv
        attributes = %w{name email age}
        CSV.generate(headers: true) do |csv|
            csv << attributes
            
            all.find_each do |user|
                csv << attributes.map{ |attr| user.send(attr) }
            end
        end
    end
end

app/models/name.rb
class Name < ApplicationRecord
    
    after_create_commit { broadcast_prepend_to "names" }
    after_update_commit { broadcast_update_to "names" }
    after_destroy_commit { broadcast_remove_to "names" }
    
    Hobby = %W{ Java C Cpp Ruby Rails }
    
end

app/models/post.rb
class Post < ApplicationRecord
    enum :status, %i(draft published shipped dispatched canceled)
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'csv'
  include HomeHelper
  
  def index
  end
  
  def add_form
    respond_to do |format|
      format.turbo_stream
        @targtes = params[:target]
    end
  end
  
  def dynamic_dropdown
     @results = CsvDatum.all
     respond_to do |format|
       format.html
       format.csv { send_data @results.to_csv, filename: "users-#{Date.today}.csv" }
     end
  end
  
  def csv_import
    file = params[:file_import] if params[:file_import].present?
    call(file)
  redirect_to drop_down_path
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: %i[ show edit update destroy ]

  # GET /names or /names.json
  def index
    @names = Name.all
  end

  # GET /names/1 or /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names or /names.json
  def create
    @name = Name.new(name_params)
  
    respond_to do |format|
      if @name.save
        format.html { redirect_to name_url(@name), notice: "Name was successfully created." }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1 or /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to name_url(@name), notice: "Name was successfully updated." }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1 or /names/1.json
  def destroy
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url, notice: "Name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_params
      params.require(:name).permit(:title, hobby: [])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_form.html.erb
<div data-controller="hello">
    <input type="text"/><a href="#" class="remove_class" data-action="click->hello#removeDiv">Remove</a>
</div>

app/views/home/add_form.turbo_stream.erb
<%= turbo_stream.append @targtes do %>
     <%= render partial: "home/form" %>
<% end %>

app/views/home/dynamic_dropdown.html.erb
<h1>This is dynamic drop down select</h1>
<div data-controller="hello" data-hello-url-value="/posts">
    <%= select_tag "country",  options_for_select([ "VISA", "MasterCard" ]), include_blank: true, data: { hello_target: "rahul",action: "change->hello#getCountry" } %>
</div>
<br/>
<div>
    <%= form_with url: csv_path, method: :post do |f| %>
            <%= f.file_field :file_import, accept: ".csv" %>
            <br/></br>
            <%= f.button "Import CSV" %>
    <% end %>
</div>
<br/>
<%= link_to "Export CSV Users", drop_down_path(format: "csv") %>

<p style="color:green;">
    <% if notice %>
          <%= notice %>
    <% end %>
</p>
<div>
    <% @results.each do |row| %>
        <%= row.name %><br/>
        <%= row.email %><br/>
        <%= row.age %><br/>
    <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= t("hello") %><br>
email = <%= t("name") %><br>

User Profile Info = <%= t("user_context.user") %>
<br>
<%= link_to t("header.menu.home"), "/posts" %> &nbsp; &nbsp; &nbsp;
<%= link_to t("header.menu.news"), "/posts" %>
<br>

<div data-controller="hello">
    
    <div data-hello-target="add_form_field" id="results">
        <%= link_to "Add Form", "/", data: { action: "click->hello#showForm" } %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/names/_form.html.erb
<%= form_with(model: name) do |form| %>
  <% if name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
        <% name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  
   <div>
   
    <% Name::Hobby.map do |key| %>
    
      <%= form.check_box :hobby, { multiple: true }, key %>  
      <%= form.label key %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/names/_name.html.erb
<div id="<%= dom_id name %>">
  <p>
    <strong>Title:</strong>
    <%= name.title %>
  </p>

</div>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Show this name", @name %> |
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Names</h1>
<%= turbo_stream_from "names" %>
<%= turbo_frame_tag "names" do  %>
<div id="names">
  <% @names.each do |name| %>
    <%= render name %>
    <p>
      <%= link_to "Show this name", name %>
    </p>
  <% end %>
</div>
<% end %>
<%= link_to "New name", new_name_path %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @name %>

<div>
  <%= link_to "Edit this name", edit_name_path(@name) %> |
  <%= link_to "Back to names", names_path %>

  <%= button_to "Destroy this name", @name, method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>